version: "3"

services:
  elasticsearch:
    container_name: elasticsearch
    image: docker.elastic.co/elasticsearch/elasticsearch-oss:6.2.3
    expose:
      - 9200
      - 9300
    environment:
      - discovery.type=single-node
  
  kibana_es:
    container_name: kibana_es
    image: docker.elastic.co/kibana/kibana-oss:6.2.3
    links:
      - elasticsearch
    ports:
      - 5601:5601
    tty: true

  kibana_go:
    container_name: kibana_go
    image: docker.elastic.co/kibana/kibana-oss:6.2.3
    links:
      - elasticsearch
    ports:
      - 5600:5601
    tty: true
    command: ["kibana", "--elasticsearch.url=http://172.17.0.1:9090/"]
